4.9. Адаптивная сетка для главной страницы
htmlacademy-adaptive/1878323-pink-24 pull request #5
Opened 2022-01-14 23:21 UTC by koteech

2022-01-16 16:14 UTC, andreysgra requested changes

2022-01-16 16:14 UTC, andreysgra commented on source/less/components/photo/upload.less
> +    width: @desktop-width;
Ширина этого блока в десктопной версии не должна превышать ширину контентной области:
![image](https://user-images.githubusercontent.com/17790771/149667804-2f493a77-f9d4-4687-88f1-4916280bc275.png)

2022-01-16 16:14 UTC, andreysgra commented on source/less/components/photo/upload.less
> +  .mixin-fill-background(@smoky-white95, 0);
Примесь `mixin-fill-background` - а почему обязательно нужно фон блока реализовывать через псевдо элемент? Ведь его проще применить к самому блоку. Это как гвозди забивать кувалдой - можно, но крайне неудобно 😄.

2022-01-18 12:50 UTC, andreysgra commented on source/index.html
> +        <div class="download-block__wrapper download-block__wrapper--half-size wrapper">
Здесь класс `wrapper` лишний, так как у родительского блока `intro` уже есть данный класс и этот блок играет роль контейнера контента. Если вы применяете тот же класс к дочернему блоку, то блок выпирает из контейнера:
![image](https://user-images.githubusercontent.com/17790771/149940237-5ca1fdbe-dd9a-404b-bec0-bf870d5e624a.png)

![image](https://user-images.githubusercontent.com/17790771/149940332-2be0345e-e491-4f18-8edd-d6097f7c53f2.png)

2022-01-18 12:50 UTC, andreysgra commented on source/less/components/photo/upload.less
> +    width: @desktop-width;
[Этот момент](https://github.com/htmlacademy-adaptive/1878323-pink-24/pull/5#discussion_r785462606) не исправлен

2022-01-18 12:51 UTC, merged

2022-01-18 13:36 UTC, koteech commented on source/less/components/photo/upload.less
> +    width: @desktop-width;
Поправил, спасибо